### ISSUE TITLE
DavinciPics update

### ISSUE THREAD

**Issue by psychoter** [EdanStasiuk/Hash-Vault#5]
Hey Edan,
Nice work on Hash-Vault, it's a great application.
Just wanted to let you know DavinciPic Component has updated to version 2. You may want to integrate it to Hash-Valut.

**Comment by EdanStasiuk** [comment]
Thanks @psychoter!
Currently aiming to construct the rest of the pages and get a viable product together so I'll leave this open for the time being and take a look at it when I get chance.

**Comment by EdanStasiuk** [comment]
Updated to version 2 in [PR #6](https://github.com/EdanStasiuk/Hash-Vault/commit/62d30fbfb8c86492a45a59ddaa72f8d041ec0446).
